<?php

/**
 * Implementation of hook_menu.
 */
function cacherouter_stats_menu() {
  $items['admin/cacherouter_stats'] = array(
    'title' => 'CacheRouter Stats',
    'page callback' => 'cacherouter_stats_admin',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('administer cacherouter stats'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'cacherouter_stats.admin.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/general'] = array(
    'title' => 'General',
    'page callback' => 'cacherouter_stats_admin',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('administer cacherouter stats'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'cacherouter_stats.admin.inc',
    'weight'           => -11,
  );
  $items['admin/cacherouter_stats/apc'] = array(
    'title' => 'APC',
    'page callback' => 'cacherouter_stats_apc_admin',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('administer cacherouter stats'),
    'type' => MENU_LOCAL_TASK,
    'file' => './apc/cacherouter_stats.apc.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/apc/general'] = array(
    'title' => 'General',
    'page callback' => 'cacherouter_stats_apc_admin',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('administer cacherouter stats'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => './apc/cacherouter_stats.apc.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/apc/host'] = array(
    'title' => 'Host',
    'page callback' => 'cacherouter_stats_apc_host',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('view cacherouter stats'),
    'type' => MENU_LOCAL_TASK,
    'file' => './apc/cacherouter_stats.apc.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/apc/system'] = array(
    'title' => 'System entries',
    'page callback' => 'cacherouter_stats_apc_system',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('view cacherouter stats'),
    'type' => MENU_LOCAL_TASK,
    'file' => './apc/cacherouter_stats.apc.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/apc/user'] = array(
    'title' => 'User Entries',
    'page callback' => 'cacherouter_stats_apc_user',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('view cacherouter stats'),
    'type' => MENU_LOCAL_TASK,
    'file' => './apc/cacherouter_stats.apc.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/apc/version'] = array(
    'title' => 'Version check',
    'page callback' => 'cacherouter_stats_apc_version',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('view cacherouter stats'),
    'type' => MENU_LOCAL_TASK,
    'file' => './apc/cacherouter_stats.apc.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/apc/full'] = array(
    'title' => 'APC Statistics',
    'page callback' => 'cacherouter_stats_apc_full',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('view cacherouter stats'),
    'type' => MENU_CALLBACK,
    'file' => './apc/cacherouter_stats.apc.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/memcache'] = array(
    'title' => 'Memcache',
    'page callback' => 'cacherouter_stats_memcache_admin',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('administer cacherouter stats'),
    'type' => MENU_LOCAL_TASK,
    'file' => './memcache/cacherouter_stats.memcache.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/memcache/general'] = array(
    'title' => 'General',
    'page callback' => 'cacherouter_stats_memcache_admin',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('administer cacherouter stats'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => './memcache/cacherouter_stats.memcache.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/memcache/servers'] = array(
    'title' => 'Servers',
    'page callback' => 'cacherouter_stats_memcache_servers',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('administer cacherouter stats'),
    'type' => MENU_LOCAL_TASK,
    'file' => './memcache/cacherouter_stats.memcache.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/memcache/host'] = array(
    'title' => 'Host statistics',
    'page callback' => 'cacherouter_stats_memcache_host',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('administer cacherouter stats'),
    'type' => MENU_LOCAL_TASK,
    'file' => './memcache/cacherouter_stats.memcache.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/memcache/variables'] = array(
    'title' => 'Variables',
    'page callback' => 'cacherouter_stats_memcache_variables',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('administer cacherouter stats'),
    'type' => MENU_LOCAL_TASK,
    'file' => './memcache/cacherouter_stats.memcache.inc',
    'weight'           => -10,
  );
  $items['admin/cacherouter_stats/memcache/full'] = array(
    'title' => 'Memcache Statistics',
    'page callback' => 'cacherouter_stats_memcache_full',
    'page arguments' => array(),
    'access callback' => 'cacherouter_stats_access_callback',
    'access arguments' => array('view cacherouter stats'),
    'type' => MENU_CALLBACK,
    'file' => './memcache/cacherouter_stats.memcache.inc',
    'weight'           => -10,
  );

  return $items;
}

/**
 * Access callback ensuring the user profile tabs are visible only to their
 * owner.
 *
 * @param $permission
 *   Required permission to view the item.
 * @param $account
 *   A user object.
 */
function cacherouter_stats_access_callback($permission, $account = NULL) {
    global $user;

    if ($account === NULL)
        return user_access($permission);

    return ($account->uid == $user->uid && user_access($permission));
}

/**
 * Implementation of hook_perm().
 */
function cacherouter_stats_perm() {
  return array('administer cacherouter stats', 'view cacherouter stats');
}
