<?php
// $Id: cacherouter.module,v 1.1.2.8 2010/08/20 21:43:46 andypost Exp $

/**
 * @file
 * Cache Router module helper.
 *
 * @author Steve Rude <steve@slantview.com>
 */

/**
 * Implementation of hook_user().
 *
 * When logged in you don't want to hit the page_fast_cache or else you will serve
 * a cached page to a logged in user.
 */
function cacherouter_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'login':
      $params = session_get_cookie_params();
      if (version_compare(PHP_VERSION, '5.2.0') >= 0) {
        setcookie('DRUPAL_UID', TRUE, $_SERVER['REQUEST_TIME'] + (60 * 60 * 24 * 30), $params['path'], $params['domain'], $params['secure'], $params['httponly']);
      }
      else {
        setcookie('DRUPAL_UID', TRUE, $_SERVER['REQUEST_TIME'] + (60 * 60 * 24 * 30), $params['path'], $params['domain'], $params['secure']);
      }
      break;

    case 'logout':
      $params = session_get_cookie_params();
      // Set in past to delete cookie
      if (version_compare(PHP_VERSION, '5.2.0') >= 0) {
        setcookie('DRUPAL_UID', TRUE, $_SERVER['REQUEST_TIME'] - 3600, $params['path'], $params['domain'], $params['secure'], $params['httponly']);
      }
      else {
        setcookie('DRUPAL_UID', TRUE, $_SERVER['REQUEST_TIME'] - 3600, $params['path'], $params['domain'], $params['secure']);
      }
      unset($_COOKIE['DRUPAL_UID']);
      break;
  }
}
